name: Build natten for Windows (CUDA 12.6)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel

      - name: Install CUDA 12.6
        run: |
          Invoke-WebRequest "https://developer.download.nvidia.com/compute/cuda/12.6.0/network_installers/cuda_12.6.0_windows_network.exe" -OutFile cuda_installer.exe
          Start-Process -FilePath ".\cuda_installer.exe" -ArgumentList "-s nvcc_12.6" -Wait
          Remove-Item cuda_installer.exe

      - name: Install CMake and Ninja
        run: |
          choco install cmake ninja -y --installargs 'ADD_CMAKE_TO_PATH=System'

      - name: Set CUDA Environment
        run: |
          $env:Path += ";C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin"
          echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build with verbose logging
        run: |
          pip install -e . --no-cache-dir
          cmake --build build --config Release --verbose  # 关键调试步骤[[2]][[5]]

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: natten-cuda126
          path: dist/*.whl
